import Head from 'next/head'
import Content from '../components/Content'
import Layout from '../components/layout'
import LeftSideNav from '../components/LeftSideNav'
import NavBar from '../components/NavBar'

export default function Home() {
  return (
    <div className='h-screen'>
      <Head>
        <title>Next-Jobs</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
<<<<<<< HEAD

=======
      
      <Layout ></Layout>
      
>>>>>>> experiment
    </div>
  )
}
