import Head from 'next/head'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Next-Jobs</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>HRllo</h1>
    </div>
  )
}
